name: .NET

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  buildProduction:
 
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/head/master'
    environment: 
      name: production
      url: https://github.com/ToveSeger/SalaryApplication/tree/master
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore


  buildDev:
 
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/head/dev'
    environment: 
      name: development
      url: https://github.com/ToveSeger/SalaryApplication/tree/dev
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

      
  testDev:
      name: testDev
      needs: buildProduction
      runs-on: ${{matrix.os}}
      strategy:
        matrix:
          os: [windows-latest, macos-latest, ubunutu-latest]
      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Test
        run: dotnet test --verbosity normal
      
      
  testProd:
      name: testProd
      needs: buildDev
      runs-on: ${{matrix.os}}
      strategy:
        matrix:
          os: [windows-latest, macos-latest, ubunutu-latest]
      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Test
        run: dotnet test --verbosity normal
      
